// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by "thema lineage gen" from lineage defined in example.cue

package main

// Example defines model for example.
type Example struct {
	Datasource struct {
		Type string  `json:"type"`
		Uid  *string `json:"uid,omitempty"`
	} `json:"datasource"`
}
