// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by "thema lineage gen" from lineage defined in *.cue

package main

// Example defines model for example.
type Example struct {
	Header string `json:"header"`
}
