// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by "thema lineage gen" from lineage defined in example.cue

package main

// Example defines model for example.
type Example struct {
	RandoSource string `json:"rando_source"`
}
